### PR TITLE
Support for Smallworld/magik

### PR DESCRIPTION
**Pull request by StevenLooman**
Support for Smallworld/magik. Requires https://github.com/emacs-lsp/lsp-mode/pull/3843

Provides:
* Attachable debugger to active Smallworld/magik session.

### CODE REVIEW

**Comment by StevenLooman** [comment]
I am unsure about the dependency/installation. Surely you can provide meaningful feedback about this.

**Comment by yyoncho** [comment]
> I am unsure about the dependency/installation. Surely you can provide meaningful feedback about this.

can you elaborate?

**Comment by StevenLooman** [comment]
This part calls a lsp-function:
https://github.com/emacs-lsp/dap-mode/pull/693/files#diff-db3504458eded196c0e0165487845fe7dd675e123adedf34a87ce51ce7782441R51-R54

I'm not sure if this is allowed and/or works as intended (read: my intention).

**Comment by yyoncho** [comment]
You may try using dap-utils-github-extension-setup-function

**Comment by StevenLooman** [comment]
I doubt this is usable in my case. The debug adapter is a release asset, for example: https://github.com/StevenLooman/magik-tools/releases/download/0.6.0/magik-debug-adapter-0.6.0.jar

**Comment by StevenLooman** [comment]
I've updated this as well as bumped the magik debug adapter version. Can you take another look @yyoncho ?

**Comment by yyoncho** [comment]
Thank you, sorry for the delay!

**Comment by StevenLooman** [comment]
No problem, fell off my radar as well.

**Pull request merged**
