### PR TITLE
dap-python, Flask support

### PR DESCRIPTION
**Pull request by DJManas**
Hi,
this commit should finally be able to launch flask app in debug mode using debugpy.

Thanks,
Regards,
Petr Sourek

### CODE REVIEW

**Comment by htgoebel** [comment]
This seems to requires setting up a template defining a module. Please provide some documentation on this, e.g an example template. This will help others to actually use this. THx.

**Comment by DJManas** [comment]
I am still new to emacs so learning pretty hardly, but I am using vscode template from .vscode/launch.json:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Home",
      "type": "python",
      "request": "launch",
      "module": "flask",
      "env": {
        "FLASK_APP": "app.py",
        "FLASK_DEBUG": "1"
      },
      "args": [
        "run",
        "--no-debugger",
        "--no-reload"
      ],
      "jinja": true,
      "justMyCode": true
    }
  ]
}
```

This works, when you launch from the project root, e.g. from app.py. I have folder hierarchy like this:
image

And when I am editing file from models directory I am unable to launch the template (even not table to use spc-d-d-l), since I am not in project root. I am switching to e.g. app.py file and launching, but I will try to sort this out in the future. At the moment I am happy, that this is working and I can debug this app under spacemacs.

**Comment by htgoebel** [comment]
@DJManas I mean: please add this to the documentation https://github.com/emacs-lsp/dap-mode/tree/master/docs/page like the tutorial for Python poetry pyenv. Nobody will search the documentation in the pull-request.

**Comment by DJManas** [comment]
Oh I am dumb, ok, I will do it in the evening. Thanks for patience.

**Comment by DJManas** [comment]
Is this comment ok, for what the change is doing? Maybee there is better way to achieve the same, I am new to lisp and emacs.

**Comment by DJManas** [comment]
Resolved documentation issue, creating new pull request.

**Pull request closed without merging**
