### PR TITLE
Update CI to work with multiple platforms

### PR DESCRIPTION
**Pull request by jcs090218**

### CODE REVIEW

**Comment by jcs090218** [comment]
All check have passed! 🎉

**Comment by jcs090218** [comment]
Can anyone review this?

@yyoncho Can you give me the push permission on this repo? I would like to put more work on this. :) Thanks!

**Comment by yyoncho** [comment]
@jcs090218 you should be good now.

**Comment by jcs090218** [comment]
Thanks! :)

**Pull request merged**
