### PR TITLE
Don't make setExceptionBreakpoints request if filters would be empty

### PR DESCRIPTION
**Pull request by themkat**
A lot of smaller debug adapters around the web does not support exception breakpoints, and a few I've tried even make the setExceptionBreakpoint request crash the adapter. (Example: some of these are assembly specific for 80s and 90s processors, like MOS). From what I can see in the specification of Debug Adapter Protocol, it is not necessary to send a setExceptionBreakpoints request if we do not have any. From the [specification](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Initialized): "frontend sends a ‘setExceptionBreakpoints’ request if one or more ‘exceptionBreakpointFilters’ have been defined (or if ‘supportsConfigurationDoneRequest’ is not defined or false)"

While we could also make all adapters handle setExceptionBreakpoints, I think it makes more sense to just not send the request in dap-mode. This is because exception breakpoints only make sense for high level languages that support exceptions (Java, Kotlin etc.).

**EDIT:** The build issues seems to be because of issues with the setup-eask action and not because of my code.

### CODE REVIEW

**Review by yyoncho — APPROVED** [review]
Thank you!

**Comment by yyoncho** [comment]
@jcs090218 can you take a look at the CI? Seems like the setup is broken?

**Comment by themkat** [comment]
I opened an issue about it https://github.com/emacs-eask/setup-eask/issues/22. Seems like @jcs090218  has fixed it now 🙂

**Comment by jcs090218** [comment]
Sorry for the inconvenience! The issue was upgrading the dependency `toolchain`; I probably should not do that in the first place. 😅 Everything is good now!

**Pull request merged**
