### PR TITLE
Name output and stderr buffers according to session name, reuse if they exist

### PR DESCRIPTION
**Pull request by lane-s**
When using dap-mode, I find that the *out* and *stderr* buffers accumulate quite
rapidly. This option uses the previously created buffers if they are found.

### CODE REVIEW

**Comment by yyoncho** [comment]
This PR cannot go as it is since you will have the output of all applications that you have started into a single buffer. If you want to reuse the output buffer you may add a hook to dap-session-created-hook and delete the output buffer on startup or use dap-terminated-hook to clean the current session's output buffer.

**Comment by lane-s** [comment]
What about if the output buffers were named according to the session name like with the stderr buffer?

**Comment by yyoncho** [comment]
> What about if the output buffers were named according to the session name like with the stderr buffer?

Make sense.

**Comment by yyoncho** [comment]
@lane-s as a side note, the initial name could be calculated base on the binary.

**Comment by lane-s** [comment]
@yyoncho Wouldn't the initial name be read from the template configuration file?

**Comment by yyoncho** [comment]
@lane-s yes, now the name comes from the template but each function that populates the arguments could override it.

**Comment by lane-s** [comment]
So is the session name not final until the `dap--session-init-resp-handler` is called?

**Comment by yyoncho** [comment]
> So is the session name not final until the `dap--session-init-resp-handler` is called?

Until `dap-start-debugging`

**Comment by lane-s** [comment]
@yyoncho So is my latest commit ok? It seems like if the session name is finalized at `dap-start-debugging`, then just changing `dap--create-session` to set `output-buffer` based on the session name should make it so that the output buffer is reused if the session name is the same, but otherwise a new buffer is created.

**Comment by yyoncho** [comment]
I will have to test that manually(I am almost done for today). We should ensure that it is not possible to have 2 debug session logging into one output buffer. Also, it would be good to do not reuse the session buffer if there is some output from the previous session, or at least if we clear it.

**Comment by lane-s** [comment]
I was thinking of just leaving the output from the previous run in the buffer. It might also be a good idea to add auto scrolling to the output buffer. I think I could do that too if you want.

There's still some problems with it though. It seems that the sessions are still in the list returned by `dap--get-sessions` even after the debugger terminates. If that's intended, then the best solution is probably just to delete session's output/stderr buffers when delete session is called. 

It also seems to me that if the session is still in the list, then you should be able to switch to it and delete, but currently this doesn't seem to be the case.

**Comment by yyoncho** [comment]
> I was thinking of just leaving the output from the previous run in the buffer. It might also be a good idea to add auto scrolling to the output buffer. I think I could do that too if you want.

I think that there is emacs mode that could do that out of the box.

> There's still some problems with it though. It seems that the sessions are still in the list returned by dap--get-sessions even after the debugger terminates. If that's intended, then the best solution is probably just to delete session's output/stderr buffers when delete session is called.
> It also seems to me that if the session is still in the list, then you should be able to switch to it and delete, but currently this doesn't seem to be the case.

You could subscribe to dap-terminate-hook and clean up the terminated session(we may introduce method `dap-cleanup-terminated-sessions`  similar to `dap-delete-all-sessions`). Note that it is virtually impossible to support all configurations out of the box, but we should make as many customizations as possible via exposing API which dap-mode users could use to customize it.

We could create a set of recipes which could be used by the users to create `their` personal debug environment. I have created one: https://github.com/emacs-lsp/dap-mode/wiki/HowTo:-Display-debug-windows-on-session-startup .

**Comment by yyoncho** [comment]
Thank you for contributing to `dap-mode`!

**Comment by yyoncho** [comment]
> It might also be a good idea to add auto scrolling to the output buffer. I think I could do that too if you want.

Someone mentioned that this works, but I am not 100% sure. 

https://emacs.stackexchange.com/questions/41242/how-to-autoscroll-a-window-to-always-show-the-end-of-a-growing-buffer/41248#41248

I haven't tried it if it does not work a PR will be much appreciated.

**Pull request merged**
