### PR TITLE
Add preliminary netcoredbg support

### PR DESCRIPTION
**Pull request by TOTBWF**
This PR implements DAP support for projects on .NET core, using the [netcoredbg](https://github.com/Samsung/netcoredbg) debugger.

TODOS:
- [x] Attach to process
- [ ] Remote debugging
- [ ] Debugging inside of docker containers

### CODE REVIEW

**Comment by yyoncho** [comment]
Thank you, it will be great if you can provide hello world project which could be used to test this in https://github.com/emacs-lsp/lsp-docker/tree/master/demo-projects .

**Comment by nosami** [comment]
Hey... I just tried this with both C# app and F# apps and it works great, cheers!

debug
debugfsharp

**Comment by yyoncho** [comment]
> Hey... I just tried this with both C# app and F# apps and it works great, cheers!
> 
> debug
> debugfsharp

Nice! 

@TOTBWF maybe we can merge it as it is and address the other issues in separate PRs?

**Comment by TOTBWF** [comment]
That sounds good. However, I no longer work with F# at my job, so I can't promise that I can provide maintenance on this. If someone else wanted to step up that would be greatly appreciated 🙂

**Comment by sebasmonia** [comment]
@nosami I had some challenges getting this to run, see https://github.com/emacs-lsp/dap-mode/issues/125#issuecomment-650406673

are you on Windows or Linux?

**Comment by nosami** [comment]
> are you on Windows or Linux?

Neither, this was on a Mac :) I guess it would work the same on linux

**Comment by sebasmonia** [comment]
hahaha :) 
but it's good info anyway, it means that the likely culprit is path conversion, like with the `expand-file-name` that I had to add for `~` that I mentioned in the issue comments.
Thanks!!!

**Comment by nosami** [comment]
> @TOTBWF maybe we can merge it as it is and address the other issues in separate PRs?

I'd want to get "Attach to process" working as it's something I'd likely use on a daily basis. Do any of the other debuggers have the capability of attaching to an already running process so I can see how it's done?

**Comment by yyoncho** [comment]
> > @TOTBWF maybe we can merge it as it is and address the other issues in separate PRs?
> 
> I'd want to get "Attach to process" working as it's something I'd likely use on a daily basis. Do any of the other debuggers have the capability of attaching to an already running process so I can see how it's done?

Check the java one. It is basically changing the launch to attach in the request. But check in package.json in the vscode extensions what are the required properties in the request.

**Comment by sebasmonia** [comment]
@TOTBWF one change needed is, each `read-file-name` needs to be wrapped in `expand-file-name`.
I got farther now by pointing to the DLL rather than the EXE. but when hitting the first breakpoint I get:
```
No message handler for capabilities
No message handler for module [9 times]
Debug session process exited with status: unknown signal
```
(the first two messages don't seem to be the problem...)
Also if I try using `System.Diagnostics.Debugger.Break();` that doesn't work...but it doesn't seem to be on dap-mode, but netcoredbg...

**Comment by yyoncho** [comment]
@sebasmonia 

> Debug session process exited with status: unknown signal

You should check the stderr buffer for the debug connection.

**Comment by sebasmonia** [comment]
`*NetCoreDbg::Launch stderr*` says `Process NetCoreDbg::Launch stderr finished`

`*NetCoreDbg::Launch out*` has the console output of the test program.
It never stopped in any breakpoints, but it did run.

**Comment by sebasmonia** [comment]
```
-> (C) {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"coreclr","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us"},"type":"request","seq":1}
<- (E) {"body":{"capabilities":{"supportTerminateDebuggee":true,"supportsConditionalBreakpoints":true,"supportsConfigurationDoneRequest":true,"supportsFunctionBreakpoints":true}},"event":"capabilities","seq":1,"type":"event"}
<- (E) {"body":{},"event":"initialized","seq":2,"type":"event"}
<- (R) {"body":{"supportTerminateDebuggee":true,"supportsConditionalBreakpoints":true,"supportsConfigurationDoneRequest":true,"supportsFunctionBreakpoints":true},"command":"initialize","request_seq":1,"seq":3,"success":true,"type":"response"}
-> (C) {"command":"setBreakpoints","arguments":{"source":{"name":"Program.cs","path":"c:/Home/debugtest/Program.cs"},"breakpoints":[{"line":32},{"line":17},{"line":13}],"sourceModified":false,"lines":[32,17,13]},"type":"request","seq":2}
<- (R) {"body":{"breakpoints":[{"id":1,"line":32,"message":"","verified":false},{"id":2,"line":17,"message":"","verified":false},{"id":3,"line":13,"message":"","verified":false}]},"command":"setBreakpoints","request_seq":2,"seq":4,"success":true,"type":"response"}
-> (C) {"command":"launch","arguments":{"type":"coreclr","request":"launch","name":"NetCoreDbg::Launch","stopAtEntry":true,"program":"c:/Home/debugtest/bin/Debug/netcoreapp2.1/debugtest.dll","dap-server-path":["c:/netcoredbg/netcoredbg.exe","--interpreter=vscode","--engineLogging=c:/log.dbg"]},"type":"request","seq":3}
<- (R) {"body":{},"command":"launch","request_seq":3,"seq":5,"success":true,"type":"response"}
-> (C) {"command":"setExceptionBreakpoints","arguments":{"filters":[]},"type":"request","seq":4}
<- (R) {"command":"setExceptionBreakpoints","message":"Failed command 'setExceptionBreakpoints' : 0x80004001","request_seq":4,"seq":6,"success":false,"type":"response"}
-> (C) {"command":"configurationDone","type":"request","seq":5}
<- (R) {"body":{},"command":"configurationDone","request_seq":5,"seq":7,"success":true,"type":"response"}
<- (E) {"body":{"module":{"id":"03b18b0c-cda1-4d73-9f96-eff40550f948","name":"System.Private.CoreLib.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.1.15\\System.Private.CoreLib.dll","symbolStatus":"Skipped loading symbols."},"reason":"new"},"event":"module","seq":8,"type":"event"}
<- (E) {"body":{"reason":"started","threadId":62396},"event":"thread","seq":9,"type":"event"}
<- (E) {"body":{"module":{"id":"f9c51670-00b5-4d9e-9bd3-1cffd3896730","name":"debugtest.dll","path":"c:\\Home\\debugtest\\bin\\Debug\\netcoreapp2.1\\debugtest.dll","symbolStatus":"Symbols not found."},"reason":"new"},"event":"module","seq":10,"type":"event"}
<- (E) {"body":{"module":{"id":"db1d0124-0d6a-48d1-8af6-47595cfe2489","name":"System.Runtime.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.1.15\\System.Runtime.dll","symbolStatus":"Skipped loading symbols."},"reason":"new"},"event":"module","seq":11,"type":"event"}
<- (E) {"body":{"module":{"id":"b789aab3-3259-4785-9c82-a9e05d6d36d1","name":"System.Diagnostics.Process.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.1.15\\System.Diagnostics.Process.dll","symbolStatus":"Skipped loading symbols."},"reason":"new"},"event":"module","seq":12,"type":"event"}
<- (E) {"body":{"module":{"id":"beb36e08-3d54-4f6e-b78b-89a5aba349e0","name":"System.ComponentModel.Primitives.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.1.15\\System.ComponentModel.Primitives.dll","symbolStatus":"Skipped loading symbols."},"reason":"new"},"event":"module","seq":13,"type":"event"}
<- (E) {"body":{"module":{"id":"0e2687e8-0e3a-49d8-baf1-667216a5461c","name":"System.Console.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.1.15\\System.Console.dll","symbolStatus":"Skipped loading symbols."},"reason":"new"},"event":"module","seq":14,"type":"event"}
-> (C) {"command":"threads","type":"request","seq":6}
<- (R) {"body":{"threads":[{"id":12344,"name":"<No name>"},{"id":62396,"name":"<No name>"}]},"command":"threads","request_seq":6,"seq":15,"success":true,"type":"response"}
<- (E) {"body":{"module":{"id":"549eb1b1-c335-4e01-8e09-b33d04d62706","name":"System.Threading.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.1.15\\System.Threading.dll","symbolStatus":"Skipped loading symbols."},"reason":"new"},"event":"module","seq":16,"type":"event"}
<- (E) {"body":{"module":{"id":"89c33d48-941a-42a6-bcf4-5fb0cab9ab40","name":"System.Runtime.Extensions.dll","path":"C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.1.15\\System.Runtime.Extensions.dll","symbolStatus":"Skipped loading symbols."},"reason":"new"},"event":"module","seq":17,"type":"event"}
<- (E) {"body":{"category":"stdout","output":"PID: 18824\r\n"},"event":"output","seq":18,"type":"event"}
<- (E) {"body":{"category":"stdout","output":"Hello World!\r\n-35\r\nKthxbye\r\n"},"event":"output","seq":19,"type":"event"}
<- (E) {"body":{"exitCode":0},"event":"exited","seq":20,"type":"event"}
<- (E) {"body":{},"event":"terminated","seq":21,"type":"event"}
```
that's the debugger output, it seems everything is ok....

**Comment by yyoncho** [comment]
@sebasmonia I had issues on windows when running jdtls with paths:

```
"path":"c:/Home/debugtest/Program.cs"
```

I manually replaced / with \ and fixed the issue. My guess is that what is happening on your side considering the fact that the breakpoints are not verified.

**Comment by sebasmonia** [comment]
Getting ahead of myself...for the attach configuration I see we need the Process ID, and then you can invoke the debugger with `--attach #PID` .

I was looking at the Java configuration and for attach it seems to use a port to connect to a running debugger, but maybe I'm misunderstanding something?
I'm leaning on something like this for the attach config, but not sure `:process-id?` is the correct parameter name :)

```
(defun dap-netcore--populate-attach-args (conf)
  "Populate CONF with the attach arguments."
  (dap--put-if-absent conf :process-id? (read-string "Process ID:"))
  (dap--put-if-absent conf :dap-server-path (list (dap-netcore--debugger-locate) "--interpreter=vscode" "--engineLogging=c:/log.dbg")))

(dap-register-debug-provider
 "coreclr-launch"
 'dap-netcore--populate-attach-args)

(dap-register-debug-template ".Net Core Launch (Console)"
                             (list :type "coreclr-launch"
                                   :request "attach"
                                   :name "NetCoreDbg::Attach"
                                   :stopAtEntry t))
```

**Comment by sebasmonia** [comment]
First point: everything works wonderfully in Linux (sadly that's not what I used at work :laughing:)

Second: @nosami use the configuration below to add Launch & Attach configurations.
```
(defun dap-netcore--populate-launch-args (conf)
  "Populate CONF with the default arguments."
  (dap--put-if-absent conf :program (expand-file-name (read-file-name "Select an executable:" (concat (lsp-workspace-root) "/bin/Debug"))))
  (dap--put-if-absent conf :dap-server-path (list (dap-netcore--debugger-locate) "--interpreter=vscode")))

(defun dap-netcore--populate-attach-args (conf)
  "Populate CONF with the attach arguments."
  (dap--put-if-absent conf :processId (string-to-number (read-string "Enter PID: " "2345")))
  (dap--put-if-absent conf :dap-server-path (list (dap-netcore--debugger-locate) "--interpreter=vscode")))

(dap-register-debug-provider
 "coreclr-attach"
 'dap-netcore--populate-attach-args)

(dap-register-debug-provider
 "coreclr-launch"
 'dap-netcore--populate-launch-args)

(dap-register-debug-template ".Net Core Attach (Console)"
                             (list :type "coreclr-attach"
                                   :request "attach"
                                   :name "NetCoreDbg::Attach"
                                   :stopAtEntry t))

(dap-register-debug-template ".Net Core Launch (Console)"
                             (list :type "coreclr-launch"
                                   :request "launch"
                                   :name "NetCoreDbg::Launch"
                                   :stopAtEntry t))
```

**Comment by yyoncho** [comment]
@sebasmonia 

> I was looking at the Java configuration and for attach it seems to use a port to connect to a running debugger, but maybe I'm misunderstanding something?

The arguments for attaching/launching in dap-mode are platform-specific

**Comment by sebasmonia** [comment]
@yyoncho thanks Ivan! I got a sample launch w/ process id config from Go and tested the code above under Linux and it worked.

To recap the changes needed on this PR:
1. Correct the concat when searching for a program from `bin/Debug` to `/bin/Debug`
2. Add `expand-file-name` when dealing with paths (read-file-name & also the paths from customization)
3. Correct the download & install code for Windows - I will re-test when I'm back to work to try to pinpoint the problem.

Changes suggested:
1. Add Attach configuration above

I guess we can work out the Windows problems later, although a lot of people looking for C# support might be using Windows. It is my case.

**Comment by nosami** [comment]
It would be great if there were a list of currently running dotnet apps to attach to instead of specifying the pid, but that could be done in a later PR.

**Comment by yyoncho** [comment]
> I guess we can work out the Windows problems later, although a lot of people looking for C# support might be using Windows. It is my case.

This is what I do to debug the app: https://github.com/emacs-lsp/dap-mode/issues/184#issuecomment-572418864 . I still believe that the issue is in setBreakpoints request because the adapter returns that it cannot set the breakpoint.

**Comment by sebasmonia** [comment]
Fired up the work laptop, regardless of changing the / for \\ it still won't work. Trying to attach the log from netcoredbg is a lot smaller, the exceptions command that fails is setExceptionBreakpoints of which I have none:
```
-> (C) {"command":"setExceptionBreakpoints","arguments":{"filters":[]},"type":"request","seq":4}
<- (R) {"command":"setExceptionBreakpoints","message":"Failed command 'setExceptionBreakpoints' : 0x80004001","request_seq":4,"seq":6,"success":false,"type":"response"}
```
I'm thinking maybe it isn't a problem. WIll confirm later if I see the same log entries in Linux.

And now using the code I paste above, I'm getting this in the messages buffer:
```
No message handler for capabilities
error in process filter: posframe--get-font-height: Args out of range: 0, 1, 1
error in process filter: Args out of range: 0, 1, 1
error in process filter: posframe--get-font-height: Args out of range: 0, 1, 1
error in process filter: Args out of range: 0, 1, 1
```

Looking at the backtrace via `debug-on-error`:
```
Debugger entered--Lisp error: (args-out-of-range 0 1 1)
  font-at(0)
  posframe--get-font-height(75)
  posframe-show(" *dap-ui*" :string #("                             " 0 4 (help-echo "Continue" pointer hand local-map (keymap (mouse-1 . dap-continue)) display (image :type png :file "c:/Home/.emacs.d/elpa/dap-mode-20200701.2046/icons..." :ascent center :background "#E5E9F0")) 5 9 (help-echo "Session not stopped?" pointer hand local-map (keymap (mouse-1)) display (image :type png :file "c:/Home/.emacs.d/elpa/dap-mode-20200701.2046/icons..." :ascent center :background "#E5E9F0")) 10 14 (help-echo "Session not stopped? " pointer hand local-map (keymap (mouse-1)) display (image :type png :file "c:/Home/.emacs.d/elpa/dap-mode-20200701.2046/icons..." :ascent center :background "#E5E9F0")) 15 19 (help-echo "Session not stopped?" pointer hand local-map (keymap (mouse-1)) display (image :type png :file "c:/Home/.emacs.d/elpa/dap-mode-20200701.2046/icons..." :ascent center :background "#E5E9F0")) 20 24 (help-echo "Disconnect" pointer hand local-map (keymap (mouse-1 . dap-disconnect)) display (image :type png :file "c:/Home/.emacs.d/elpa/dap-mode-20200701.2046/icons..." :ascent center :background "#E5E9F0")) 25 29 (help-echo "Restart" pointer hand local-map (keymap (mouse-1 . dap-debug-restart)) display (image :type png :file "c:/Home/.emacs.d/elpa/dap-mode-20200701.2046/icons..." :ascent center :background "#E5E9F0"))) :poshandler posframe-poshandler-frame-top-center :internal-border-width 8)
  dap-ui--update-controls()
  run-hook-with-args(dap-ui--update-controls)
  dap--set-sessions((#s(dap--debug-session :name "NetCoreDbg::Launch" :last-id 3 :proc #<process NetCoreDbg::Launch> :response-handlers #<hash-table eql 3/65 0x2482ded> :parser #s(dap--parser :waiting-for-response nil :response-result nil :headers nil :body nil :reading-body nil :body-length nil :body-received nil :leftovers "") :output-buffer #<buffer *NetCoreDbg::Launch out*> :thread-id nil :workspace nil :threads nil :thread-states #<hash-table eql 0/65 0x2482f15> :active-frame-id nil :active-frame nil :cursor-marker nil :state pending :breakpoints #<hash-table equal 0/65 0x2482f35> :thread-stack-frames #<hash-table eql 0/65 0x2482f55> :launch-args (:type "coreclr-launch" :request "launch" :name "NetCoreDbg::Launch" :stopAtEntry t :program "c:/Home/debugtest/bin/Debug/netcoreapp2.1/debugtes..." :dap-server-path ("c:/netcoredbg/netcoredbg.exe" "--interpreter=vscode" "--engineLogging=c:/home/debugtest/log.txt")) :initialize-result #<hash-table equal 6/65 0x265b08d> :error-message nil :loaded-sources nil :program-proc nil :metadata #<hash-table eql 0/65 0x25e8795>)))
  #f(compiled-function (initialize-result) #<bytecode -0x983244a27bae0e7>)(#<hash-table equal 6/65 0x265b08d>)
  #f(compiled-function (input0) #<bytecode -0x7887c80fcd2f7ab>)(#<hash-table equal 6/65 0x265b08d>)
  #f(compiled-function (m) #<bytecode 0x372143ba592f3be>)("{\"body\":{\"supportTerminateDebuggee\":true,\"supports...")
  mapc(#f(compiled-function (m) #<bytecode 0x372143ba592f3be>) ("{\"body\":{\"capabilities\":{\"supportTerminateDebuggee..." "{\"body\":{},\"event\":\"initialized\",\"seq\":2,\"type\":\"e..." "{\"body\":{\"supportTerminateDebuggee\":true,\"supports..."))
  #f(compiled-function (_ msg) #<bytecode 0x631e729d1740fcd>)(#<process NetCoreDbg::Launch> "Content-Length: 218\15\n\15\n{\"body\":{\"capabilities\":{\"s...")
  read-event(nil t 2)
  sit-for(2)
  execute-extended-command(nil "dap-debug" nil)
  funcall-interactively(execute-extended-command nil "dap-debug" nil)
  #<subr call-interactively>(execute-extended-command nil nil)
  apply(#<subr call-interactively> execute-extended-command (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> execute-extended-command nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (execute-extended-command nil nil))
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

I compiled Emacs 28 from master 2020-06-17, all packages up to date.  Maybe something changed in a function used by 
posframe, but the Emacs I use in my personal laptop is probably even newer (`-git` package from AUR...) 

We could use one more Windows tester 🤔

**Comment by sebasmonia** [comment]
`setExceptionsBreakpoints` doesn't fail in Linux.
Maybe it is a debugger bug.

**Comment by yyoncho** [comment]
@sebasmonia IMO the problematic call is setBreakpoints not setExceptionBreakpoints.

> Debugger entered--Lisp error: (args-out-of-range 0 1 1)
  font-at(0)
  posframe--get-font-height(75)
  posframe-show(" *dap-ui*" :string #("          

This is `posframe` issue.

**Comment by sebasmonia** [comment]
Don't get the `posframe` error anymore, but still can't debug on Windows. 
I tried setting up the test project ouside the `~` dir, and changing the breakpoints file to use \\ instead of /, but no luck.

**Comment by yyoncho** [comment]
> Don't get the `posframe` error anymore, but still can't debug on Windows.
> I tried setting up the test project ouside the `~` dir, and changing the breakpoints file to use \ instead of /, but no luck.

I suggest doing [this](https://github.com/emacs-lsp/dap-mode/issues/184#issuecomment-572418864) and capturing the vscode breakpoints call(or the whole communication vscode-debug adater). 

Without this information, it is guesswork ...

**Comment by sebasmonia** [comment]
But, since it worked in Linux and MacOS, I think it does work. The problem is elsewhere, in the Win environment. It might not even be dap-mode's fault, could be the debugger too.

**Comment by yyoncho** [comment]
> But, since it worked in Linux and MacOS, I think it does work. The problem is elsewhere, in the Win environment. It might not even be dap-mode's fault, could be the debugger too.

Most likely is adapter being more restrictive on something, or expecting something that we are not sending but vscode is sending. That is why I am suggesting comparing the vscode io log with dap-mode's io log.

**Comment by sebasmonia** [comment]
The reason the install fails on Windows is that it assumes the extension is `.tar.gz`.
In `dap-netcore--debugger-install` the definition of `temp-file` should be:
```
(make-temp-file "netcoredbg" nil
                                    (if (eq system-type 'windows-nt)
                                        ".zip"
                                      ".tar.gz"))
```
And then that part works :)

(Recently the debugger had a few fixes related to breakpoints so I'm re-testing)

**Comment by ksjogo** [comment]
Should this work with mono projects? I would like to debug my Godot projects from Emacs.

**Comment by yyoncho** [comment]
> Should this work with mono projects? I would like to debug my Godot projects from Emacs.

I don't know if this pr will work with mono but there is https://github.com/microsoft/vscode-mono-debug which will work.

**Comment by mslot** [comment]
I am currently trying to figure out how to do this for Azure Functions. It is a bit hard to see, because I need to start an Azure Function with `func start` in the same directory as the `.csproj`.

How do I attach to a running process? I have tried to use the same launch.json as in VS Code, but VS Code uses a parameter that is specific to VS Code `${command:azureFunctions.pickProcess}`.

Full launch.json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to .NET Functions",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:azureFunctions.pickProcess}"
        }
    ]
}

This wont work. Does anyone here know of a method to:
1. start a process, and then
2. attach to the process

or is this simply not possible?
```

**Comment by nbfalcon** [comment]
I am generally aiming for launch.json feature parity with VSCode, so I will look into implementing at least command:pickProcess and the azure function one and get back to you.

**Comment by mslot** [comment]
> I am generally aiming for launch.json feature parity with VSCode, so I will look into implementing at least command:pickProcess and the azure function one and get back to you.

Is there any way I can help? How do I get started? I have really tried to find some writings on how dap can be triggered.

This is the only thing I need to be fully running on spacemacs with c#. I really feel like I can contribute with more if I know how to expand dap when we talk csharp.

**Comment by nbfalcon** [comment]
I have implemented ${command:pickProcess}, which should at least be a starting point. The process selection is a bit awkward, since it doesn't filter by user processes (I figured some people with docker might have problems if their containers run as some other user).

As for extending dap/contributing to open source: the best way to get started imho is to find some problem you have with some package (in my case: I didn't like specifying debug configurations in dir-locals and wanted to use launch.json files). If you don't have any problems, but still want to contribute, you can just look trough the issue tracker and fix various issues of other people.

Regarding adding variables: the entire expansion code is in dap-variables.el, the entry point to which is `dap-variables-expand-in-launch-configuration`. You can add most variables by implementing them in `dap-variables-launch-configuration-variables`, whose docstring you should see, as I always take care to document my work thoroughly. If that is not enough, you should look at `dap-variables-pre-expand-hook`, `dap-variables-post-expand-hook`, `dap-variables-pre-expand-variables` and `dap-variables-numbered-prompts`. Note that I will soon refactor this module into a separate package.

**Comment by nbfalcon** [comment]
If you could tell me what ${command:azureFunctions.pickProcess} does, I can implement it too, or you can try implementing it yourself.

**Comment by mslot** [comment]
@nbfalcon that is my approach as well, I want work and expand on the things I find useful, fx this. I actually don't know what the {command:azureFunctions.pickProcess} does. It is something VSCode generates out of the box. I will try your updates tonight when I have time.

**Comment by mslot** [comment]
@nbfalcon I actually think that ${command:azureFunctions.pickProcess} does this:
1. it calls "func start" in project root
2. wait some time (maybe 60 sec - i have this from https://github.com/microsoft/vscode-azurefunctions/issues/436)
3. look for the azure function process
4. attach to it

This is my guess. I have seen your work on your own fork. I want to try this out and maybe give a go at the ${command:azureFunctions.pickProcess}. I just need to figure out how to load your fork into my current spacemacs configuration and take it from there.

**Comment by nbfalcon** [comment]
@mslot I haven't just implemented it in my fork; its in current master (since I am a dap contributor, I can push directly to master; this makes my fork redundant. The only reason its still there is for "decorative purposes"), so load mainline dap instead. My fork is actually behind. As for loading dap, there isn't really any elegant solution in spacemacs. I have a local checkout of dap, and I abuse load-file in my .spacemacs.d/init.el to load all the files that I have made changes to.

**Comment by mslot** [comment]
@nbfalcon ah :) I see. I will pull and try it out. As to the local development, the load-file was what i was thinking about doing. I will try to research a bit more on the azure command and see what i can come up with.

Thanks for all the help. You are doing a tremendous big job for open source and emacs.

**Comment by sebasmonia** [comment]
@TOTBWF  @yyoncho can we merge this since it works in Linux and macOS?
It needs a couple of the corrections shared above, though.

**Comment by yyoncho** [comment]
@sebasmonia done. If will be great if someone updates the docs.

**Comment by yyoncho** [comment]
Continuation here - https://github.com/emacs-lsp/dap-mode/pull/363

**Pull request merged**
