### PR TITLE
#188 fix to go debug mode

### PR DESCRIPTION
**Pull request by apmattil**
fix to go debug mode:

- fix to dap-go.el
- instructions readme.org

### CODE REVIEW

**Comment by yyoncho** [comment]
Thank you!

**Comment by apmattil** [comment]
you are wellcome.. this forced me learn tiny bit of lisp after 20+ years of using emacs ;)

**Comment by yyoncho** [comment]
@apmattil there is so much work to be done so without the help of the community it will be impossible to catch up with editors like vscode which have dedicated teams.

**Comment by apmattil** [comment]
well first thing that came to my mind when I saw the nodejs stuff was 'we
should have dap support to gopls'.. as it already acts as lsp server.

**Comment by apmattil** [comment]
google is already doing go-dap: https://github.com/google/go-dap

I can try to give it a test run.
When you start the nodejs and give the GoDebug.js as parameter.. it uses
stdio for communication ?

Br,
Ari

**Comment by yyoncho** [comment]
> When you start the nodejs and give the GoDebug.js as parameter.. it uses
stdio for communication ?

yes.

**Pull request merged**
